-- Executive Financial Performance dataset
CREATE TABLE financial_data (
  Date DATE,
  Year INT,
  "Month Number" INT,
  "Month Name" TEXT,
  Product TEXT,
  Segment TEXT,
  Country TEXT,
  "Units Sold" INT,
  "Sale Price" NUMERIC(10,2),
  "Manufacturing Price" NUMERIC(10,2),
  "Gross Sales" NUMERIC(14,2),
  Discounts NUMERIC(14,2),
  Sales NUMERIC(14,2),
  COGS NUMERIC(14,2),
  Profit NUMERIC(14,2),
  "Profit Margin" NUMERIC(7,4),
  "Total Expenses" NUMERIC(14,2),
  "Actual Expenses" NUMERIC(14,2),
  "Net Income" NUMERIC(14,2),
  Inventory NUMERIC(14,2),
  "Total assets" NUMERIC(14,2),
  Liabilities NUMERIC(14,2),
  Equity NUMERIC(14,2),
  "Current Ratio" NUMERIC(10,4),
  "Quick Ratio" NUMERIC(10,4),
  "Debt-to-Equity Ratio" NUMERIC(10,4),
  "Return on Assets" NUMERIC(10,4),
  "Discount Band" TEXT
);
